// ─── FreeSWITCH Config Sync ──────────────────────────────────────────────────
// Generates FreeSWITCH gateway XML from HeyHank trunk settings and triggers reload.
// This is the bridge between "user enters SIP credentials in UI" and "FreeSWITCH registers with provider".

import { writeFileSync, mkdirSync, existsSync, unlinkSync, readdirSync } from "node:fs";
import { join } from "node:path";
import type { SipTrunkConfig } from "./call-types.js";
import { getSettings } from "./telephony-store.js";
import { eslRescanGateways, eslGatewayStatus } from "./esl-client.js";

// The Docker volume mount maps this directory into the FreeSWITCH container
const GATEWAY_DIR = join(process.cwd(), "..", "freeswitch", "conf", "sip_profiles", "external");

// Known SIP provider defaults
const PROVIDER_DEFAULTS: Record<string, { realm: string; proxy: string; tls?: boolean }> = {
  peoplefone: { realm: "sips.peoplefone.at", proxy: "sips.peoplefone.at", tls: true },
  sipgate: { realm: "sipgate.de", proxy: "sipgate.de" },
  easybell: { realm: "sip.easybell.de", proxy: "sip.easybell.de" },
};

/**
 * Generate FreeSWITCH gateway XML for a single SIP trunk.
 */
function generateGatewayXml(trunk: SipTrunkConfig): string {
  const defaults = PROVIDER_DEFAULTS[trunk.provider];
  const realm = trunk.server || defaults?.realm || trunk.server;
  const proxy = trunk.server || defaults?.proxy || trunk.server;
  const useTls = defaults?.tls || trunk.server?.startsWith("sips.");

  // Sanitize the gateway name for FreeSWITCH (alphanumeric + underscore + hyphen)
  const gatewayName = trunk.name.replace(/[^a-zA-Z0-9_-]/g, "_").toLowerCase();

  const tlsParams = useTls ? `
    <param name="register-transport" value="tls"/>
    <param name="contact-params" value="transport=tls"/>` : "";

  return `<!-- Auto-generated by HeyHank — trunk: ${trunk.name} (${trunk.provider}) -->
<!-- DO NOT EDIT: This file is regenerated when trunk settings change in HeyHank UI -->
<include>
  <gateway name="${gatewayName}">
    <param name="username" value="${escapeXml(trunk.username)}"/>
    <param name="password" value="${escapeXml(trunk.password)}"/>
    <param name="realm" value="${escapeXml(realm)}"/>
    <param name="proxy" value="${escapeXml(proxy)}"/>
    <param name="register" value="${trunk.enabled ? "true" : "false"}"/>
    <param name="expire-seconds" value="600"/>
    <param name="caller-id-in-from" value="true"/>
    <param name="codec-prefs" value="PCMA,PCMU"/>${tlsParams}
  </gateway>
</include>
`;
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/**
 * Write all trunk configs as FreeSWITCH gateway XML files.
 * Old auto-generated files are cleaned up first.
 */
export function syncGatewayConfigs(trunks: SipTrunkConfig[]): { written: string[]; errors: string[] } {
  const written: string[] = [];
  const errors: string[] = [];

  if (!existsSync(GATEWAY_DIR)) {
    try {
      mkdirSync(GATEWAY_DIR, { recursive: true });
    } catch (err) {
      errors.push(`Cannot create gateway dir: ${err}`);
      return { written, errors };
    }
  }

  // Remove old auto-generated gateway files (identified by "heyhank_" prefix)
  try {
    const existing = readdirSync(GATEWAY_DIR).filter((f) => f.startsWith("heyhank_") && f.endsWith(".xml"));
    for (const file of existing) {
      try {
        unlinkSync(join(GATEWAY_DIR, file));
      } catch { /* ignore */ }
    }
  } catch { /* dir might not exist yet */ }

  // Write new gateway files
  for (const trunk of trunks) {
    if (!trunk.username || !trunk.password || !trunk.server) {
      errors.push(`Trunk "${trunk.name}" skipped: missing credentials`);
      continue;
    }

    const gatewayName = trunk.name.replace(/[^a-zA-Z0-9_-]/g, "_").toLowerCase();
    const filename = `heyhank_${gatewayName}.xml`;
    const filepath = join(GATEWAY_DIR, filename);

    try {
      const xml = generateGatewayXml(trunk);
      writeFileSync(filepath, xml, "utf-8");
      written.push(filename);
    } catch (err) {
      errors.push(`Failed to write ${filename}: ${err}`);
    }
  }

  return { written, errors };
}

/**
 * Sync gateway configs AND tell FreeSWITCH to reload them.
 * This is the main function called when trunk settings change in the UI.
 */
export async function syncAndReload(): Promise<{
  synced: boolean;
  reloaded: boolean;
  written: string[];
  errors: string[];
}> {
  const settings = getSettings();
  const { written, errors } = syncGatewayConfigs(settings.trunks);

  let reloaded = false;

  // Try to reload FreeSWITCH gateway profiles via ESL TCP
  if (written.length > 0) {
    try {
      reloaded = await eslRescanGateways(settings.freeswitch);
    } catch (err) {
      errors.push(`FreeSWITCH reload failed: ${err}`);
    }
  }

  return { synced: written.length > 0, reloaded, written, errors };
}

/**
 * Check if a specific gateway is registered with FreeSWITCH.
 */
export async function checkGatewayStatus(
  gatewayName: string,
): Promise<{ registered: boolean; status: string }> {
  const settings = getSettings();
  return eslGatewayStatus(gatewayName, settings.freeswitch);
}
