// ─── Google Media APIs ───────────────────────────────────────────────────────
// Image generation (Imagen 4 + Gemini) and Video generation (Veo) via Google AI APIs

import { mkdirSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { HEYHANK_HOME } from "./paths.js";

// ─── Constants ───────────────────────────────────────────────────────────────

const MEDIA_DIR = join(HEYHANK_HOME, "media");
const API_KEY = () => process.env.GOOGLE_API_KEY || process.env.GEMINI_API_KEY || "";

// Models that use the predict endpoint (Imagen)
const PREDICT_MODELS = new Set([
  "imagen-4.0-generate-001",
  "imagen-4.0-ultra-generate-001",
  "imagen-4.0-fast-generate-001",
]);

// ─── Types ───────────────────────────────────────────────────────────────────

export interface ImageGenerationResult {
  filename: string;
  path: string;
  mimeType: string;
  prompt: string;
  model: string;
}

export interface VideoGenerationResult {
  operationName: string;
  status: "pending" | "completed" | "failed";
  prompt: string;
  model: string;
  videoPath?: string;
}

// ─── Image Generation ────────────────────────────────────────────────────────

/**
 * Generate an image. Dispatches to the right API based on model:
 * - imagen-4.0-*: uses predict endpoint
 * - gemini-*: uses generateContent with IMAGE modality
 */
export async function generateImage(
  prompt: string,
  opts?: {
    model?: string;
    aspectRatio?: string;
    numberOfImages?: number;
  },
): Promise<ImageGenerationResult[]> {
  const apiKey = API_KEY();
  if (!apiKey) throw new Error("GOOGLE_API_KEY not configured");

  mkdirSync(MEDIA_DIR, { recursive: true });

  const model = opts?.model || "imagen-4.0-fast-generate-001";

  if (PREDICT_MODELS.has(model)) {
    return generateImageImagen(prompt, model, apiKey, opts);
  }
  return generateImageGemini(prompt, model, apiKey);
}

/** Imagen 4.0 via predict endpoint */
async function generateImageImagen(
  prompt: string,
  model: string,
  apiKey: string,
  opts?: { aspectRatio?: string; numberOfImages?: number },
): Promise<ImageGenerationResult[]> {
  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${model}:predict?key=${apiKey}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        instances: [{ prompt }],
        parameters: {
          sampleCount: opts?.numberOfImages || 1,
          aspectRatio: opts?.aspectRatio || "1:1",
        },
      }),
    },
  );

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Imagen API error ${response.status}: ${text}`);
  }

  const data = await response.json() as {
    predictions?: Array<{
      bytesBase64Encoded?: string;
      mimeType?: string;
    }>;
  };

  const results: ImageGenerationResult[] = [];
  for (const pred of data.predictions || []) {
    if (pred.bytesBase64Encoded) {
      const mime = pred.mimeType || "image/png";
      const ext = mime.includes("png") ? "png" : "jpg";
      const filename = `img_${Date.now()}_${Math.random().toString(36).slice(2, 8)}.${ext}`;
      const filepath = join(MEDIA_DIR, filename);
      writeFileSync(filepath, Buffer.from(pred.bytesBase64Encoded, "base64"));
      results.push({ filename, path: filepath, mimeType: mime, prompt, model });
    }
  }

  if (results.length === 0) throw new Error("No image generated by Imagen");
  return results;
}

/** Gemini models with IMAGE response modality */
async function generateImageGemini(
  prompt: string,
  model: string,
  apiKey: string,
): Promise<ImageGenerationResult[]> {
  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [{ parts: [{ text: `Generate an image: ${prompt}` }] }],
        generationConfig: { responseModalities: ["TEXT", "IMAGE"] },
      }),
    },
  );

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Gemini image API error ${response.status}: ${text}`);
  }

  const data = await response.json() as {
    candidates?: Array<{
      content?: {
        parts?: Array<{
          text?: string;
          inlineData?: { mimeType: string; data: string };
        }>;
      };
    }>;
  };

  const results: ImageGenerationResult[] = [];
  for (const candidate of data.candidates || []) {
    for (const part of candidate.content?.parts || []) {
      if (part.inlineData) {
        const ext = part.inlineData.mimeType === "image/png" ? "png" : "jpg";
        const filename = `img_${Date.now()}_${Math.random().toString(36).slice(2, 8)}.${ext}`;
        const filepath = join(MEDIA_DIR, filename);
        writeFileSync(filepath, Buffer.from(part.inlineData.data, "base64"));
        results.push({ filename, path: filepath, mimeType: part.inlineData.mimeType, prompt, model });
      }
    }
  }

  if (results.length === 0) {
    const textResponse = data.candidates?.[0]?.content?.parts?.find(p => p.text)?.text;
    throw new Error(
      textResponse
        ? `Model returned text instead of image: ${textResponse.slice(0, 200)}`
        : "No image generated",
    );
  }

  return results;
}

// ─── Video Generation (Veo) ──────────────────────────────────────────────────

/**
 * Start video generation using Google's Veo model.
 * Returns an operation that can be polled for completion.
 */
export async function generateVideo(
  prompt: string,
  opts?: {
    model?: string;
    durationSeconds?: number;
    aspectRatio?: string;
    imageUri?: string;
  },
): Promise<VideoGenerationResult> {
  const apiKey = API_KEY();
  if (!apiKey) throw new Error("GOOGLE_API_KEY not configured");

  mkdirSync(MEDIA_DIR, { recursive: true });

  const model = opts?.model || "veo-3.1-fast-generate-preview";

  const requestBody: Record<string, unknown> = {
    instances: [
      {
        prompt,
        ...(opts?.imageUri ? { image: { gcsUri: opts.imageUri } } : {}),
      },
    ],
    parameters: {
      aspectRatio: opts?.aspectRatio || "16:9",
      durationSeconds: opts?.durationSeconds || 5,
      sampleCount: 1,
      personGeneration: "allow_adult",
    },
  };

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${model}:predictLongRunning?key=${apiKey}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(requestBody),
    },
  );

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Veo API error ${response.status}: ${text}`);
  }

  const data = await response.json() as {
    name?: string;
    done?: boolean;
    error?: { message: string };
  };

  if (data.error) {
    throw new Error(`Veo error: ${data.error.message}`);
  }

  return {
    operationName: data.name || "unknown",
    status: data.done ? "completed" : "pending",
    prompt,
    model,
  };
}

/**
 * Poll a Veo video generation operation for completion.
 */
export async function pollVideoOperation(
  operationName: string,
): Promise<VideoGenerationResult & { videoData?: string }> {
  const apiKey = API_KEY();
  if (!apiKey) throw new Error("GOOGLE_API_KEY not configured");

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/${operationName}?key=${apiKey}`,
  );

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Poll error ${response.status}: ${text}`);
  }

  const data = await response.json() as {
    name: string;
    done?: boolean;
    error?: { message: string };
    response?: {
      // Veo format: generateVideoResponse with download URIs
      generateVideoResponse?: {
        generatedSamples?: Array<{
          video?: { uri?: string; encoding?: string };
        }>;
      };
      // Legacy format: predictions with base64
      predictions?: Array<{
        bytesBase64Encoded?: string;
        mimeType?: string;
      }>;
    };
  };

  if (data.error) {
    return { operationName, status: "failed", prompt: "", model: "" };
  }

  if (!data.done) {
    return { operationName, status: "pending", prompt: "", model: "" };
  }

  mkdirSync(MEDIA_DIR, { recursive: true });
  let videoPath: string | undefined;

  // Try Veo format first (download URI)
  const sample = data.response?.generateVideoResponse?.generatedSamples?.[0];
  if (sample?.video?.uri) {
    const apiKey = API_KEY();
    const videoUrl = sample.video.uri.includes("?")
      ? `${sample.video.uri}&key=${apiKey}`
      : `${sample.video.uri}?key=${apiKey}`;
    const videoResponse = await fetch(videoUrl);
    if (videoResponse.ok) {
      const buffer = Buffer.from(await videoResponse.arrayBuffer());
      const filename = `vid_${Date.now()}_${Math.random().toString(36).slice(2, 8)}.mp4`;
      videoPath = join(MEDIA_DIR, filename);
      writeFileSync(videoPath, buffer);
    }
  }

  // Fallback: predictions with base64
  if (!videoPath) {
    const prediction = data.response?.predictions?.[0];
    if (prediction?.bytesBase64Encoded) {
      const ext = prediction.mimeType === "video/webm" ? "webm" : "mp4";
      const filename = `vid_${Date.now()}_${Math.random().toString(36).slice(2, 8)}.${ext}`;
      videoPath = join(MEDIA_DIR, filename);
      writeFileSync(videoPath, Buffer.from(prediction.bytesBase64Encoded, "base64"));
    }
  }

  return {
    operationName,
    status: "completed",
    prompt: "",
    model: "",
    videoPath,
    videoData: videoPath ? "(saved to disk)" : undefined,
  };
}

/** List generated media files. */
export function listMedia(): Array<{ filename: string; path: string }> {
  mkdirSync(MEDIA_DIR, { recursive: true });
  try {
    const files = readdirSync(MEDIA_DIR) as string[];
    return files.map((f: string) => ({
      filename: f,
      path: join(MEDIA_DIR, f),
    }));
  } catch {
    return [];
  }
}
