// ─── IgWizardTab ─────────────────────────────────────────────────────────────
// Claude-driven replacement for hooksgenerator.ai + ctagenerator.ai. User types
// a niche, gets 20 viral hooks + 30 CTAs (Engagement/Leads/Growth) generated by
// Claude via /api/ig-wizard/generate. Clicking a hook or CTA copies it to the
// clipboard.
//
// Each Lead-CTA is a complete package — CTA line + trigger keyword + matching
// DM template — and gets a "Create Auto-DM Rule" button that wires the package
// straight into the Auto-DM tab. This closes the funnel loop in one click:
// caption → comment → auto-DM, no manual setup.

import { useState, useCallback, useMemo } from "react";
import { igWizardApi, autoDmRulesApi, type IgWizardResult, type IgWizardLeadPackage } from "../api.js";

interface Props {
  showMessage: (text: string, isError?: boolean) => void;
}

type CtaCategory = "engagement" | "leads" | "growth";

const CATEGORY_LABELS: Record<CtaCategory, string> = {
  engagement: "Engagement",
  leads: "Leads (Auto-DM)",
  growth: "Growth",
};

const CATEGORY_DESCRIPTIONS: Record<CtaCategory, string> = {
  engagement: "Drive likes, saves, shares, tags — algorithmic boosters.",
  leads: "Comment-triggered DM funnels. The ALL-CAPS keyword maps 1:1 to an Auto-DM rule.",
  growth: "Convert viewers into followers.",
};

/**
 * Extract the ALL-CAPS trigger word from a Leads-CTA. Used as a fallback when
 * the model returned a legacy string-shaped lead instead of the full
 * {cta, trigger, dmTemplate} package. Exported for testability.
 *
 * Returns the first ALL-CAPS word in the CTA that isn't a known verb-acronym
 * or stop-word (DM, CTA, AI, ...). This handles strings like "DM LINK for the
 * trial" where "DM" is the verb and "LINK" is the actual trigger.
 */
export function extractTriggerWord(cta: string): string | null {
  // Verb-acronyms that look like ALL-CAPS triggers but are usually the verb,
  // plus common short stop-words that we don't want to suggest as Auto-DM
  // keywords (too noisy — "AI", "URL" would match too many comments).
  const STOP = new Set([
    "DM", "CTA", "AI", "API", "URL", "BIO", "STOP",
    "NOW", "FREE", "HIT", "ME", "MY", "TAG", "VS",
  ]);
  const matches = cta.matchAll(/\b["']?([A-Z]{2,20})["']?\b/g);
  for (const m of matches) {
    const word = m[1];
    if (!STOP.has(word)) return word;
  }
  return null;
}

export function IgWizardTab({ showMessage }: Props) {
  const [niche, setNiche] = useState("");
  const [language, setLanguage] = useState<"en" | "de">("en");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<IgWizardResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [activeCategory, setActiveCategory] = useState<CtaCategory>("leads");

  const handleGenerate = useCallback(async () => {
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const res = await igWizardApi.generate(niche.trim(), language);
      setResult(res);
      showMessage("Wizard ready — pick a hook + CTA for your next Reel.");
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      setError(msg);
      showMessage(`Generate failed: ${msg}`, true);
    } finally {
      setLoading(false);
    }
  }, [niche, language, showMessage]);

  const handleCopy = useCallback(
    async (text: string, label: string) => {
      try {
        await navigator.clipboard.writeText(text);
        showMessage(`Copied ${label} to clipboard.`);
      } catch {
        showMessage("Clipboard unavailable — select + copy manually.", true);
      }
    },
    [showMessage],
  );

  // Per-lead "rule created" state, keyed by trigger keyword so collisions are
  // visible. Once a rule for "AUTOMATE" exists the button on every lead with
  // the same trigger flips to disabled with a "Created" badge.
  const [createdRuleTriggers, setCreatedRuleTriggers] = useState<Set<string>>(new Set());
  const [creatingRuleTrigger, setCreatingRuleTrigger] = useState<string | null>(null);

  const handleCreateRule = useCallback(
    async (lead: IgWizardLeadPackage) => {
      if (!lead.trigger || !lead.dmTemplate) {
        showMessage("Lead is missing a trigger keyword or DM template — can't create a rule.", true);
        return;
      }
      setCreatingRuleTrigger(lead.trigger);
      try {
        await autoDmRulesApi.create({
          platform: "instagram",
          keyword: lead.trigger,
          dmTemplate: lead.dmTemplate,
          enabled: true,
          notes: `Auto-created from IG Wizard (niche: ${result?.niche ?? "?"})`,
        });
        setCreatedRuleTriggers((prev) => new Set(prev).add(lead.trigger));
        showMessage(`Auto-DM rule created for "${lead.trigger}".`);
      } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : String(e);
        showMessage(`Failed to create Auto-DM rule: ${msg}`, true);
      } finally {
        setCreatingRuleTrigger(null);
      }
    },
    [result, showMessage],
  );

  const activeStringCtas: string[] = useMemo(() => {
    if (!result || activeCategory === "leads") return [];
    return result.ctas[activeCategory];
  }, [result, activeCategory]);
  const activeLeadCtas: IgWizardLeadPackage[] = useMemo(() => {
    if (!result || activeCategory !== "leads") return [];
    return result.ctas.leads;
  }, [result, activeCategory]);

  return (
    <div className="ig-wizard-tab" data-testid="ig-wizard-tab">
      <header style={{ marginBottom: 16 }}>
        <h2 style={{ margin: "0 0 4px 0" }}>Instagram Wizard</h2>
        <p style={{ margin: 0, color: "var(--text-muted, #888)", fontSize: 14 }}>
          Type your niche, get 20 viral hooks and 30 CTAs generated by Claude. The Leads
          CTAs map 1:1 to Auto-DM rules.
        </p>
      </header>

      <section
        aria-label="Niche input"
        style={{
          display: "flex",
          gap: 8,
          alignItems: "center",
          marginBottom: 24,
          flexWrap: "wrap",
        }}
      >
        <label htmlFor="ig-wizard-niche" style={{ fontWeight: 500 }}>
          Niche
        </label>
        <input
          id="ig-wizard-niche"
          type="text"
          value={niche}
          onChange={(e) => setNiche(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter" && !loading && niche.trim()) handleGenerate();
          }}
          placeholder="e.g. AI productivity for solopreneurs"
          style={{ flex: "1 1 280px", minWidth: 200, padding: "8px 10px" }}
          disabled={loading}
        />
        <label htmlFor="ig-wizard-language" className="sr-only" style={{ position: "absolute", left: "-9999px" }}>
          Language
        </label>
        <select
          id="ig-wizard-language"
          aria-label="Output language"
          value={language}
          onChange={(e) => setLanguage(e.target.value as "en" | "de")}
          disabled={loading}
          style={{ padding: "8px 10px" }}
        >
          <option value="en">English</option>
          <option value="de">Deutsch</option>
        </select>
        <button
          type="button"
          onClick={handleGenerate}
          disabled={loading}
          aria-label="Generate hooks and CTAs"
          style={{
            padding: "8px 16px",
            background: loading ? "var(--btn-disabled, #ccc)" : "var(--btn-primary, #0066cc)",
            color: "white",
            border: "none",
            borderRadius: 4,
            cursor: loading ? "wait" : "pointer",
            fontWeight: 500,
          }}
        >
          {loading ? "Generating…" : "Generate"}
        </button>
      </section>

      {error && (
        <div
          role="alert"
          style={{
            padding: 12,
            marginBottom: 16,
            background: "var(--alert-bg, #fee)",
            border: "1px solid var(--alert-border, #f99)",
            borderRadius: 4,
            color: "var(--alert-text, #800)",
          }}
        >
          <strong>Error:</strong> {error}
        </div>
      )}

      {!result && !loading && !error && (
        <div
          style={{
            padding: 24,
            textAlign: "center",
            color: "var(--text-muted, #888)",
            border: "1px dashed var(--border, #ccc)",
            borderRadius: 6,
          }}
        >
          <p style={{ margin: "0 0 8px 0" }}>
            Replaces hooksgenerator.ai + ctagenerator.ai with Claude. Faster, on-brand, and
            the Leads CTAs auto-pair with the Auto-DM tab.
          </p>
          <p style={{ margin: 0, fontSize: 12 }}>
            Tip: keep the niche broad ("AI for creators") to ride the algorithm's mass-appeal
            bias from the 2026 Reels playbook.
          </p>
        </div>
      )}

      {result && (
        <>
          <section aria-labelledby="ig-wizard-hooks-heading" style={{ marginBottom: 24 }}>
            <h3 id="ig-wizard-hooks-heading" style={{ marginTop: 0 }}>
              Hooks <span style={{ fontWeight: 400, color: "var(--text-muted, #888)" }}>
                ({result.hooks.length})
              </span>
            </h3>
            <p style={{ margin: "0 0 8px 0", color: "var(--text-muted, #888)", fontSize: 13 }}>
              Use as the first line of your Reel. Stop the scroll in the first 1-3 seconds.
            </p>
            <ul
              style={{
                listStyle: "none",
                padding: 0,
                margin: 0,
                display: "grid",
                gap: 6,
              }}
            >
              {result.hooks.map((hook, idx) => (
                <li key={idx}>
                  <button
                    type="button"
                    onClick={() => handleCopy(hook, "hook")}
                    aria-label={`Copy hook: ${hook}`}
                    style={{
                      width: "100%",
                      textAlign: "left",
                      padding: "8px 12px",
                      background: "var(--card-bg, #f8f8f8)",
                      border: "1px solid var(--border, #ddd)",
                      borderRadius: 4,
                      cursor: "pointer",
                      fontSize: 14,
                    }}
                  >
                    <span style={{ color: "var(--text-muted, #888)", marginRight: 8 }}>{idx + 1}.</span>
                    {hook}
                  </button>
                </li>
              ))}
            </ul>
          </section>

          <section aria-labelledby="ig-wizard-ctas-heading">
            <h3 id="ig-wizard-ctas-heading" style={{ marginTop: 0 }}>
              CTAs{" "}
              <span style={{ fontWeight: 400, color: "var(--text-muted, #888)" }}>
                ({result.ctas.engagement.length + result.ctas.leads.length + result.ctas.growth.length})
              </span>
            </h3>
            <p style={{ margin: "0 0 8px 0", color: "var(--text-muted, #888)", fontSize: 13 }}>
              Put in the <em>first</em> line of your caption — most viewers don't read past it.
            </p>
            <div role="tablist" aria-label="CTA categories" style={{ display: "flex", gap: 4, marginBottom: 8 }}>
              {(["leads", "engagement", "growth"] as CtaCategory[]).map((cat) => (
                <button
                  key={cat}
                  type="button"
                  role="tab"
                  aria-selected={activeCategory === cat}
                  aria-controls={`ig-wizard-ctas-${cat}`}
                  onClick={() => setActiveCategory(cat)}
                  style={{
                    padding: "6px 12px",
                    background: activeCategory === cat ? "var(--btn-primary, #0066cc)" : "transparent",
                    color: activeCategory === cat ? "white" : "var(--text, #333)",
                    border: "1px solid var(--border, #ddd)",
                    borderRadius: 4,
                    cursor: "pointer",
                    fontSize: 13,
                  }}
                >
                  {CATEGORY_LABELS[cat]} ({result.ctas[cat].length})
                </button>
              ))}
            </div>
            <p
              id="ig-wizard-cta-description"
              style={{ margin: "0 0 8px 0", color: "var(--text-muted, #888)", fontSize: 12 }}
            >
              {CATEGORY_DESCRIPTIONS[activeCategory]}
            </p>
            <div
              id={`ig-wizard-ctas-${activeCategory}`}
              role="tabpanel"
              aria-labelledby="ig-wizard-ctas-heading"
            >
              {activeCategory === "leads" ? (
                <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "grid", gap: 10 }}>
                  {activeLeadCtas.map((lead, idx) => (
                    <li key={`${lead.trigger}-${idx}`}>
                      <LeadCtaCard
                        index={idx}
                        lead={lead}
                        ruleCreated={createdRuleTriggers.has(lead.trigger)}
                        creating={creatingRuleTrigger === lead.trigger}
                        onCopy={() => handleCopy(lead.cta, "CTA")}
                        onCreateRule={() => handleCreateRule(lead)}
                      />
                    </li>
                  ))}
                </ul>
              ) : (
                <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "grid", gap: 6 }}>
                  {activeStringCtas.map((cta, idx) => (
                    <li key={idx}>
                      <button
                        type="button"
                        onClick={() => handleCopy(cta, "CTA")}
                        aria-label={`Copy CTA: ${cta}`}
                        style={{
                          width: "100%",
                          textAlign: "left",
                          padding: "8px 12px",
                          background: "var(--card-bg, #f8f8f8)",
                          border: "1px solid var(--border, #ddd)",
                          borderRadius: 4,
                          cursor: "pointer",
                          fontSize: 14,
                        }}
                      >
                        <span style={{ color: "var(--text-muted, #888)", marginRight: 8 }}>{idx + 1}.</span>
                        {cta}
                      </button>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </section>
        </>
      )}
    </div>
  );
}

// ─── LeadCtaCard ─────────────────────────────────────────────────────────────

interface LeadCtaCardProps {
  index: number;
  lead: IgWizardLeadPackage;
  ruleCreated: boolean;
  creating: boolean;
  onCopy: () => void;
  onCreateRule: () => void;
}

/**
 * Renders a single Lead-CTA package: the CTA caption line, the trigger keyword
 * badge, the DM-template preview, and a "Create Auto-DM Rule" button that
 * wires the package into the Auto-DM tab in one click. Disabled + checkmark
 * once the rule has been created in this session.
 */
function LeadCtaCard({ index, lead, ruleCreated, creating, onCopy, onCreateRule }: LeadCtaCardProps) {
  const canCreate = Boolean(lead.trigger && lead.dmTemplate);
  return (
    <article
      style={{
        background: "var(--card-bg, #f8f8f8)",
        border: "1px solid var(--border, #ddd)",
        borderRadius: 6,
        padding: 10,
        display: "grid",
        gap: 6,
      }}
      aria-label={`Lead CTA ${index + 1} with trigger ${lead.trigger || "unknown"}`}
    >
      <div style={{ display: "flex", alignItems: "flex-start", gap: 8 }}>
        <span style={{ color: "var(--text-muted, #888)", fontSize: 13, paddingTop: 2 }}>{index + 1}.</span>
        <button
          type="button"
          onClick={onCopy}
          aria-label={`Copy CTA: ${lead.cta}`}
          style={{
            flex: 1,
            textAlign: "left",
            background: "transparent",
            border: "none",
            padding: 0,
            cursor: "pointer",
            fontSize: 14,
            color: "var(--text, #333)",
          }}
        >
          {lead.cta}
        </button>
        {lead.trigger && (
          <span
            aria-label={`Trigger keyword: ${lead.trigger}`}
            style={{
              fontFamily: "monospace",
              fontSize: 12,
              padding: "2px 6px",
              background: "var(--badge-bg, #e8f0fe)",
              color: "var(--badge-text, #1565c0)",
              borderRadius: 3,
              whiteSpace: "nowrap",
            }}
          >
            {lead.trigger}
          </span>
        )}
      </div>
      {lead.dmTemplate && (
        <div
          aria-label="Suggested DM template"
          style={{
            fontSize: 12,
            color: "var(--text-muted, #666)",
            background: "var(--code-bg, #fff)",
            border: "1px dashed var(--border, #ddd)",
            borderRadius: 4,
            padding: "6px 8px",
            fontFamily: "system-ui, sans-serif",
            whiteSpace: "pre-wrap",
          }}
        >
          <span style={{ fontWeight: 600, color: "var(--text-muted, #888)" }}>DM reply:</span>{" "}
          {lead.dmTemplate}
        </div>
      )}
      <div style={{ display: "flex", gap: 8, justifyContent: "flex-end", marginTop: 2 }}>
        {ruleCreated ? (
          <span
            role="status"
            aria-label="Rule created"
            style={{
              fontSize: 12,
              padding: "4px 10px",
              background: "var(--success-bg, #e6f4ea)",
              color: "var(--success-text, #137333)",
              borderRadius: 4,
              fontWeight: 500,
            }}
          >
            ✓ Auto-DM rule created
          </span>
        ) : (
          <button
            type="button"
            onClick={onCreateRule}
            disabled={!canCreate || creating}
            aria-label={`Create Auto-DM rule for trigger ${lead.trigger}`}
            title={
              canCreate
                ? "Create an Instagram Auto-DM rule from this package (you can edit it later in the Auto-DM tab)"
                : "This lead is missing a trigger keyword or DM template — re-generate."
            }
            style={{
              fontSize: 12,
              padding: "4px 10px",
              background: !canCreate || creating ? "var(--btn-disabled, #ccc)" : "var(--btn-primary, #0066cc)",
              color: "white",
              border: "none",
              borderRadius: 4,
              cursor: !canCreate || creating ? "not-allowed" : "pointer",
              fontWeight: 500,
            }}
          >
            {creating ? "Creating…" : "Create Auto-DM Rule"}
          </button>
        )}
      </div>
    </article>
  );
}
