// ─── IgWizardTab ─────────────────────────────────────────────────────────────
// Claude-driven replacement for hooksgenerator.ai + ctagenerator.ai. User types
// a niche, gets 20 viral hooks + 30 CTAs (Engagement/Leads/Growth) generated by
// Claude via /api/ig-wizard/generate. Clicking a hook or CTA copies it to the
// clipboard.
//
// Each Lead-CTA is a complete package — CTA line + trigger keyword + matching
// DM template — and gets a "Create Auto-DM Rule" button that wires the package
// straight into the Auto-DM tab. This closes the funnel loop in one click:
// caption → comment → auto-DM, no manual setup.

import { useState, useCallback, useMemo } from "react";
import {
  igWizardApi,
  autoDmRulesApi,
  type IgWizardResult,
  type IgWizardLeadPackage,
  type IgCaptionResult,
  type IgPlanResult,
  type IgPlanBrief,
} from "../api.js";

type WizardMode = "single" | "plan";

const CTA_TYPE_LABELS: Record<IgPlanBrief["ctaType"], string> = {
  lead: "Lead",
  engagement: "Engagement",
  growth: "Growth",
};

interface Props {
  showMessage: (text: string, isError?: boolean) => void;
}

type CtaCategory = "engagement" | "leads" | "growth";

const CATEGORY_LABELS: Record<CtaCategory, string> = {
  engagement: "Engagement",
  leads: "Leads (Auto-DM)",
  growth: "Growth",
};

const CATEGORY_DESCRIPTIONS: Record<CtaCategory, string> = {
  engagement: "Drive likes, saves, shares, tags — algorithmic boosters.",
  leads: "Comment-triggered DM funnels. The ALL-CAPS keyword maps 1:1 to an Auto-DM rule.",
  growth: "Convert viewers into followers.",
};

/**
 * Extract the ALL-CAPS trigger word from a Leads-CTA. Used as a fallback when
 * the model returned a legacy string-shaped lead instead of the full
 * {cta, trigger, dmTemplate} package. Exported for testability.
 *
 * Returns the first ALL-CAPS word in the CTA that isn't a known verb-acronym
 * or stop-word (DM, CTA, AI, ...). This handles strings like "DM LINK for the
 * trial" where "DM" is the verb and "LINK" is the actual trigger.
 */
export function extractTriggerWord(cta: string): string | null {
  // Verb-acronyms that look like ALL-CAPS triggers but are usually the verb,
  // plus common short stop-words that we don't want to suggest as Auto-DM
  // keywords (too noisy — "AI", "URL" would match too many comments).
  const STOP = new Set([
    "DM", "CTA", "AI", "API", "URL", "BIO", "STOP",
    "NOW", "FREE", "HIT", "ME", "MY", "TAG", "VS",
  ]);
  const matches = cta.matchAll(/\b["']?([A-Z]{2,20})["']?\b/g);
  for (const m of matches) {
    const word = m[1];
    if (!STOP.has(word)) return word;
  }
  return null;
}

export function IgWizardTab({ showMessage }: Props) {
  const [mode, setMode] = useState<WizardMode>("single");
  const [niche, setNiche] = useState("");
  const [language, setLanguage] = useState<"en" | "de">("en");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<IgWizardResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [activeCategory, setActiveCategory] = useState<CtaCategory>("leads");

  // ── 30-Day Plan state ───────────────────────────────────────────────────────
  const [planTopic, setPlanTopic] = useState("");
  const [planResult, setPlanResult] = useState<IgPlanResult | null>(null);
  const [planLoading, setPlanLoading] = useState(false);
  const [planError, setPlanError] = useState<string | null>(null);

  const handleGenerate = useCallback(async () => {
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const res = await igWizardApi.generate(niche.trim(), language);
      setResult(res);
      showMessage("Wizard ready — pick a hook + CTA for your next Reel.");
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      setError(msg);
      showMessage(`Generate failed: ${msg}`, true);
    } finally {
      setLoading(false);
    }
  }, [niche, language, showMessage]);

  const handleCopy = useCallback(
    async (text: string, label: string) => {
      try {
        await navigator.clipboard.writeText(text);
        showMessage(`Copied ${label} to clipboard.`);
      } catch {
        showMessage("Clipboard unavailable — select + copy manually.", true);
      }
    },
    [showMessage],
  );

  // Per-lead "rule created" state, keyed by trigger keyword so collisions are
  // visible. Once a rule for "AUTOMATE" exists the button on every lead with
  // the same trigger flips to disabled with a "Created" badge.
  const [createdRuleTriggers, setCreatedRuleTriggers] = useState<Set<string>>(new Set());
  const [creatingRuleTrigger, setCreatingRuleTrigger] = useState<string | null>(null);

  // ── Caption Composer state ──────────────────────────────────────────────────
  // Assembles a full ready-to-post caption from the niche (+ an optional hook /
  // CTA the user picked from the lists above) via /api/ig-wizard/caption.
  const [composerHook, setComposerHook] = useState("");
  const [composerCta, setComposerCta] = useState("");
  const [caption, setCaption] = useState<IgCaptionResult | null>(null);
  const [composing, setComposing] = useState(false);

  const handleCompose = useCallback(async () => {
    setComposing(true);
    setCaption(null);
    try {
      const res = await igWizardApi.caption({
        topic: niche.trim(),
        language,
        hook: composerHook.trim() || undefined,
        cta: composerCta.trim() || undefined,
      });
      setCaption(res);
      showMessage("Caption composed — copy + paste into Instagram.");
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      showMessage(`Compose failed: ${msg}`, true);
    } finally {
      setComposing(false);
    }
  }, [niche, language, composerHook, composerCta, showMessage]);

  const useHookInComposer = useCallback((hook: string) => {
    setComposerHook(hook);
    showMessage("Hook added to the Caption Composer below.");
  }, [showMessage]);

  const useCtaInComposer = useCallback((cta: string) => {
    setComposerCta(cta);
    showMessage("CTA added to the Caption Composer below.");
  }, [showMessage]);

  const handlePlan = useCallback(async () => {
    setPlanLoading(true);
    setPlanError(null);
    setPlanResult(null);
    try {
      const res = await igWizardApi.plan({ topic: planTopic.trim(), language, days: 30 });
      setPlanResult(res);
      showMessage(`30-day plan ready — ${res.briefs.length} post ideas. Tap a day to compose it.`);
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      setPlanError(msg);
      showMessage(`Plan failed: ${msg}`, true);
    } finally {
      setPlanLoading(false);
    }
  }, [planTopic, language, showMessage]);

  // Jump a plan brief into the Single-Post composer: seed the hook + the topic
  // (so the caption is about the same thing) and switch to Single mode where the
  // composer lives.
  const composeBrief = useCallback((brief: IgPlanBrief) => {
    setComposerHook(brief.hook);
    setComposerCta("");
    if (planTopic.trim()) setNiche(planTopic.trim());
    setMode("single");
    showMessage(`Day ${brief.day} loaded into the Caption Composer.`);
  }, [planTopic, showMessage]);

  const handleCreateRule = useCallback(
    async (lead: IgWizardLeadPackage) => {
      if (!lead.trigger || !lead.dmTemplate) {
        showMessage("Lead is missing a trigger keyword or DM template — can't create a rule.", true);
        return;
      }
      setCreatingRuleTrigger(lead.trigger);
      try {
        await autoDmRulesApi.create({
          platform: "instagram",
          keyword: lead.trigger,
          dmTemplate: lead.dmTemplate,
          enabled: true,
          notes: `Auto-created from IG Wizard (niche: ${result?.niche ?? "?"})`,
        });
        setCreatedRuleTriggers((prev) => new Set(prev).add(lead.trigger));
        showMessage(`Auto-DM rule created for "${lead.trigger}".`);
      } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : String(e);
        showMessage(`Failed to create Auto-DM rule: ${msg}`, true);
      } finally {
        setCreatingRuleTrigger(null);
      }
    },
    [result, showMessage],
  );

  const activeStringCtas: string[] = useMemo(() => {
    if (!result || activeCategory === "leads") return [];
    return result.ctas[activeCategory];
  }, [result, activeCategory]);
  const activeLeadCtas: IgWizardLeadPackage[] = useMemo(() => {
    if (!result || activeCategory !== "leads") return [];
    return result.ctas.leads;
  }, [result, activeCategory]);

  return (
    <div className="ig-wizard-tab" data-testid="ig-wizard-tab">
      <header style={{ marginBottom: 16 }}>
        <h2 style={{ margin: "0 0 4px 0" }}>Instagram Wizard</h2>
        <p style={{ margin: 0, color: "var(--text-muted, #888)", fontSize: 14 }}>
          Hooks, CTAs + full captions for a single post — or a whole month of post ideas from one topic.
        </p>
      </header>

      <div role="tablist" aria-label="Wizard mode" style={{ display: "flex", gap: 4, marginBottom: 20 }}>
        {([
          { id: "single" as const, label: "📝 Single Post" },
          { id: "plan" as const, label: "📅 30-Day Plan" },
        ]).map((m) => (
          <button
            key={m.id}
            type="button"
            role="tab"
            aria-selected={mode === m.id}
            onClick={() => setMode(m.id)}
            style={{
              padding: "8px 16px",
              background: mode === m.id ? "var(--btn-primary, #0066cc)" : "transparent",
              color: mode === m.id ? "white" : "var(--text, #333)",
              border: "1px solid var(--border, #ddd)",
              borderRadius: 4,
              cursor: "pointer",
              fontWeight: 500,
              fontSize: 14,
            }}
          >
            {m.label}
          </button>
        ))}
      </div>

      {mode === "single" && (
       <>

      <section
        aria-label="Niche input"
        style={{
          display: "flex",
          gap: 8,
          alignItems: "center",
          marginBottom: 24,
          flexWrap: "wrap",
        }}
      >
        <label htmlFor="ig-wizard-niche" style={{ fontWeight: 500 }}>
          Niche
        </label>
        <input
          id="ig-wizard-niche"
          type="text"
          value={niche}
          onChange={(e) => setNiche(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter" && !loading && niche.trim()) handleGenerate();
          }}
          placeholder="e.g. AI productivity for solopreneurs"
          style={{ flex: "1 1 280px", minWidth: 200, padding: "8px 10px" }}
          disabled={loading}
        />
        <label htmlFor="ig-wizard-language" className="sr-only" style={{ position: "absolute", left: "-9999px" }}>
          Language
        </label>
        <select
          id="ig-wizard-language"
          aria-label="Output language"
          value={language}
          onChange={(e) => setLanguage(e.target.value as "en" | "de")}
          disabled={loading}
          style={{ padding: "8px 10px" }}
        >
          <option value="en">English</option>
          <option value="de">Deutsch</option>
        </select>
        <button
          type="button"
          onClick={handleGenerate}
          disabled={loading}
          aria-label="Generate hooks and CTAs"
          style={{
            padding: "8px 16px",
            background: loading ? "var(--btn-disabled, #ccc)" : "var(--btn-primary, #0066cc)",
            color: "white",
            border: "none",
            borderRadius: 4,
            cursor: loading ? "wait" : "pointer",
            fontWeight: 500,
          }}
        >
          {loading ? "Generating…" : "Generate"}
        </button>
      </section>

      {error && (
        <div
          role="alert"
          style={{
            padding: 12,
            marginBottom: 16,
            background: "var(--alert-bg, #fee)",
            border: "1px solid var(--alert-border, #f99)",
            borderRadius: 4,
            color: "var(--alert-text, #800)",
          }}
        >
          <strong>Error:</strong> {error}
        </div>
      )}

      {!result && !loading && !error && !composerHook && !composerCta && (
        <div
          style={{
            padding: 24,
            textAlign: "center",
            color: "var(--text-muted, #888)",
            border: "1px dashed var(--border, #ccc)",
            borderRadius: 6,
          }}
        >
          <p style={{ margin: "0 0 8px 0" }}>
            Replaces hooksgenerator.ai + ctagenerator.ai with Claude. Faster, on-brand, and
            the Leads CTAs auto-pair with the Auto-DM tab.
          </p>
          <p style={{ margin: 0, fontSize: 12 }}>
            Tip: keep the niche broad ("AI for creators") to ride the algorithm's mass-appeal
            bias from the 2026 Reels playbook.
          </p>
        </div>
      )}

      {result && (
        <>
          <section aria-labelledby="ig-wizard-hooks-heading" style={{ marginBottom: 24 }}>
            <h3 id="ig-wizard-hooks-heading" style={{ marginTop: 0 }}>
              Hooks <span style={{ fontWeight: 400, color: "var(--text-muted, #888)" }}>
                ({result.hooks.length})
              </span>
            </h3>
            <p style={{ margin: "0 0 8px 0", color: "var(--text-muted, #888)", fontSize: 13 }}>
              Use as the first line of your Reel. Stop the scroll in the first 1-3 seconds.
            </p>
            <ul
              style={{
                listStyle: "none",
                padding: 0,
                margin: 0,
                display: "grid",
                gap: 6,
              }}
            >
              {result.hooks.map((hook, idx) => (
                <li key={idx} style={{ display: "flex", gap: 6 }}>
                  <button
                    type="button"
                    onClick={() => handleCopy(hook, "hook")}
                    aria-label={`Copy hook: ${hook}`}
                    style={{
                      flex: 1,
                      textAlign: "left",
                      padding: "8px 12px",
                      background: "var(--card-bg, #f8f8f8)",
                      border: "1px solid var(--border, #ddd)",
                      borderRadius: 4,
                      cursor: "pointer",
                      fontSize: 14,
                    }}
                  >
                    <span style={{ color: "var(--text-muted, #888)", marginRight: 8 }}>{idx + 1}.</span>
                    {hook}
                  </button>
                  <button
                    type="button"
                    onClick={() => useHookInComposer(hook)}
                    aria-label={`Use hook in caption composer: ${hook}`}
                    title="Use in Caption Composer"
                    style={{
                      flex: "0 0 auto",
                      padding: "8px 10px",
                      background: "transparent",
                      border: "1px solid var(--border, #ddd)",
                      borderRadius: 4,
                      cursor: "pointer",
                      fontSize: 13,
                      whiteSpace: "nowrap",
                    }}
                  >
                    ✍️ Use
                  </button>
                </li>
              ))}
            </ul>
          </section>

          <section aria-labelledby="ig-wizard-ctas-heading">
            <h3 id="ig-wizard-ctas-heading" style={{ marginTop: 0 }}>
              CTAs{" "}
              <span style={{ fontWeight: 400, color: "var(--text-muted, #888)" }}>
                ({result.ctas.engagement.length + result.ctas.leads.length + result.ctas.growth.length})
              </span>
            </h3>
            <p style={{ margin: "0 0 8px 0", color: "var(--text-muted, #888)", fontSize: 13 }}>
              Put in the <em>first</em> line of your caption — most viewers don't read past it.
            </p>
            <div role="tablist" aria-label="CTA categories" style={{ display: "flex", gap: 4, marginBottom: 8 }}>
              {(["leads", "engagement", "growth"] as CtaCategory[]).map((cat) => (
                <button
                  key={cat}
                  type="button"
                  role="tab"
                  aria-selected={activeCategory === cat}
                  aria-controls={`ig-wizard-ctas-${cat}`}
                  onClick={() => setActiveCategory(cat)}
                  style={{
                    padding: "6px 12px",
                    background: activeCategory === cat ? "var(--btn-primary, #0066cc)" : "transparent",
                    color: activeCategory === cat ? "white" : "var(--text, #333)",
                    border: "1px solid var(--border, #ddd)",
                    borderRadius: 4,
                    cursor: "pointer",
                    fontSize: 13,
                  }}
                >
                  {CATEGORY_LABELS[cat]} ({result.ctas[cat].length})
                </button>
              ))}
            </div>
            <p
              id="ig-wizard-cta-description"
              style={{ margin: "0 0 8px 0", color: "var(--text-muted, #888)", fontSize: 12 }}
            >
              {CATEGORY_DESCRIPTIONS[activeCategory]}
            </p>
            <div
              id={`ig-wizard-ctas-${activeCategory}`}
              role="tabpanel"
              aria-labelledby="ig-wizard-ctas-heading"
            >
              {activeCategory === "leads" ? (
                <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "grid", gap: 10 }}>
                  {activeLeadCtas.map((lead, idx) => (
                    <li key={`${lead.trigger}-${idx}`}>
                      <LeadCtaCard
                        index={idx}
                        lead={lead}
                        ruleCreated={createdRuleTriggers.has(lead.trigger)}
                        creating={creatingRuleTrigger === lead.trigger}
                        onCopy={() => handleCopy(lead.cta, "CTA")}
                        onCreateRule={() => handleCreateRule(lead)}
                        onUseInComposer={() => useCtaInComposer(lead.cta)}
                      />
                    </li>
                  ))}
                </ul>
              ) : (
                <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "grid", gap: 6 }}>
                  {activeStringCtas.map((cta, idx) => (
                    <li key={idx}>
                      <button
                        type="button"
                        onClick={() => handleCopy(cta, "CTA")}
                        aria-label={`Copy CTA: ${cta}`}
                        style={{
                          width: "100%",
                          textAlign: "left",
                          padding: "8px 12px",
                          background: "var(--card-bg, #f8f8f8)",
                          border: "1px solid var(--border, #ddd)",
                          borderRadius: 4,
                          cursor: "pointer",
                          fontSize: 14,
                        }}
                      >
                        <span style={{ color: "var(--text-muted, #888)", marginRight: 8 }}>{idx + 1}.</span>
                        {cta}
                      </button>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          </section>
        </>
      )}

      {(result || composerHook || composerCta) && (
        <section aria-labelledby="ig-wizard-composer-heading" style={{ marginTop: 28, paddingTop: 20, borderTop: "1px solid var(--border, #ddd)" }}>
            <h3 id="ig-wizard-composer-heading" style={{ marginTop: 0 }}>📝 Caption Composer</h3>
            <p style={{ margin: "0 0 12px 0", color: "var(--text-muted, #888)", fontSize: 13 }}>
              Turn a hook + CTA into a complete, ready-to-post caption (hook · value lines · CTA · hashtags).
              Hit <strong>✍️ Use</strong> on any hook or lead CTA above to drop it in, or leave blank to let Claude pick.
            </p>

            <div style={{ display: "grid", gap: 8, marginBottom: 12 }}>
              <div>
                <label htmlFor="composer-hook" style={{ display: "block", fontSize: 12, color: "var(--text-muted, #888)", marginBottom: 2 }}>
                  Hook (optional)
                </label>
                <input
                  id="composer-hook"
                  type="text"
                  value={composerHook}
                  onChange={(e) => setComposerHook(e.target.value)}
                  placeholder="Leave blank to let Claude pick the strongest hook"
                  style={{ width: "100%", padding: "8px 10px", boxSizing: "border-box" }}
                  disabled={composing}
                />
              </div>
              <div>
                <label htmlFor="composer-cta" style={{ display: "block", fontSize: 12, color: "var(--text-muted, #888)", marginBottom: 2 }}>
                  Lead CTA (optional)
                </label>
                <input
                  id="composer-cta"
                  type="text"
                  value={composerCta}
                  onChange={(e) => setComposerCta(e.target.value)}
                  placeholder="e.g. Comment GUIDE for my free AI workflow ⚡"
                  style={{ width: "100%", padding: "8px 10px", boxSizing: "border-box" }}
                  disabled={composing}
                />
              </div>
            </div>

            <button
              type="button"
              onClick={handleCompose}
              disabled={composing}
              aria-label="Compose full caption"
              style={{
                padding: "8px 16px",
                background: composing ? "var(--btn-disabled, #ccc)" : "var(--btn-primary, #0066cc)",
                color: "white",
                border: "none",
                borderRadius: 4,
                cursor: composing ? "wait" : "pointer",
                fontWeight: 500,
              }}
            >
              {composing ? "Composing…" : "Compose Caption"}
            </button>

            {caption && (
              <div style={{ marginTop: 16 }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 6 }}>
                  <span style={{ fontSize: 13, fontWeight: 500 }}>Your caption</span>
                  <button
                    type="button"
                    onClick={() => handleCopy(caption.caption, "caption")}
                    aria-label="Copy full caption"
                    style={{
                      padding: "5px 12px",
                      background: "var(--btn-primary, #0066cc)",
                      color: "white",
                      border: "none",
                      borderRadius: 4,
                      cursor: "pointer",
                      fontSize: 13,
                    }}
                  >
                    📋 Copy caption
                  </button>
                </div>
                <textarea
                  readOnly
                  aria-label="Composed caption"
                  value={caption.caption}
                  rows={Math.min(16, caption.caption.split("\n").length + 2)}
                  style={{
                    width: "100%",
                    boxSizing: "border-box",
                    padding: "10px 12px",
                    fontSize: 14,
                    lineHeight: 1.5,
                    fontFamily: "inherit",
                    background: "var(--card-bg, #f8f8f8)",
                    border: "1px solid var(--border, #ddd)",
                    borderRadius: 4,
                    resize: "vertical",
                  }}
                />
                {caption.hashtags.length > 0 && (
                  <p style={{ margin: "6px 0 0 0", fontSize: 12, color: "var(--text-muted, #888)" }}>
                    {caption.hashtags.length} hashtags · {caption.language.toUpperCase()}
                  </p>
                )}
              </div>
            )}
        </section>
      )}
       </>
      )}

      {mode === "plan" && (
        <PlanMode
          topic={planTopic}
          setTopic={setPlanTopic}
          language={language}
          loading={planLoading}
          error={planError}
          result={planResult}
          onGenerate={handlePlan}
          onCompose={composeBrief}
        />
      )}
    </div>
  );
}

// ─── PlanMode (30-Day Plan) ──────────────────────────────────────────────────

const CTA_TYPE_COLORS: Record<IgPlanBrief["ctaType"], { bg: string; fg: string }> = {
  lead: { bg: "var(--badge-bg, #e8f0fe)", fg: "var(--badge-text, #1565c0)" },
  engagement: { bg: "#fce8e6", fg: "#c5221f" },
  growth: { bg: "#e6f4ea", fg: "#137333" },
};

interface PlanModeProps {
  topic: string;
  setTopic: (v: string) => void;
  language: "en" | "de";
  loading: boolean;
  error: string | null;
  result: IgPlanResult | null;
  onGenerate: () => void;
  onCompose: (brief: IgPlanBrief) => void;
}

/**
 * The "30-Day Plan" mode: one topic → a month of distinct post ideas. Each day
 * is a light brief (angle + hook + ctaType). Tapping "Compose" hands the brief
 * to the Single-Post Caption Composer to expand into a full caption.
 */
function PlanMode({ topic, setTopic, language, loading, error, result, onGenerate, onCompose }: PlanModeProps) {
  return (
    <div>
      <section
        aria-label="Plan topic input"
        style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 20, flexWrap: "wrap" }}
      >
        <label htmlFor="ig-plan-topic" style={{ fontWeight: 500 }}>Topic</label>
        <input
          id="ig-plan-topic"
          type="text"
          value={topic}
          onChange={(e) => setTopic(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter" && !loading) onGenerate();
          }}
          placeholder="e.g. self-hosting AI tools to cut SaaS costs"
          style={{ flex: "1 1 280px", minWidth: 200, padding: "8px 10px" }}
          disabled={loading}
        />
        <button
          type="button"
          onClick={onGenerate}
          disabled={loading}
          aria-label="Generate 30-day plan"
          style={{
            padding: "8px 16px",
            background: loading ? "var(--btn-disabled, #ccc)" : "var(--btn-primary, #0066cc)",
            color: "white",
            border: "none",
            borderRadius: 4,
            cursor: loading ? "wait" : "pointer",
            fontWeight: 500,
          }}
        >
          {loading ? "Planning…" : "Generate 30-Day Plan"}
        </button>
      </section>

      {error && (
        <div role="alert" style={{ padding: 12, marginBottom: 16, background: "var(--alert-bg, #fee)", border: "1px solid var(--alert-border, #f99)", borderRadius: 4, color: "var(--alert-text, #800)" }}>
          <strong>Error:</strong> {error}
        </div>
      )}

      {!result && !loading && !error && (
        <div style={{ padding: 24, textAlign: "center", color: "var(--text-muted, #888)", border: "1px dashed var(--border, #ccc)", borderRadius: 6 }}>
          <p style={{ margin: "0 0 8px 0" }}>
            One topic → 30 distinct post ideas. Each day rotates a different angle so the feed never repeats.
          </p>
          <p style={{ margin: 0, fontSize: 12 }}>
            Tap <strong>Compose</strong> on any day to expand its hook into a full caption.
          </p>
        </div>
      )}

      {result && (
        <section aria-labelledby="ig-plan-heading">
          <h3 id="ig-plan-heading" style={{ marginTop: 0 }}>
            {result.briefs.length}-Day Plan{" "}
            <span style={{ fontWeight: 400, color: "var(--text-muted, #888)" }}>· {result.topic}</span>
          </h3>
          <ol style={{ listStyle: "none", padding: 0, margin: 0, display: "grid", gap: 8 }}>
            {result.briefs.map((brief) => (
              <li
                key={brief.day}
                style={{
                  display: "flex",
                  alignItems: "flex-start",
                  gap: 10,
                  padding: 10,
                  background: "var(--card-bg, #f8f8f8)",
                  border: "1px solid var(--border, #ddd)",
                  borderRadius: 6,
                }}
              >
                <span style={{ fontWeight: 600, color: "var(--text-muted, #888)", fontSize: 13, minWidth: 48 }}>
                  Day {brief.day}
                </span>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontSize: 14, fontWeight: 500, marginBottom: 2 }}>{brief.hook}</div>
                  <div style={{ fontSize: 12, color: "var(--text-muted, #666)" }}>{brief.angle}</div>
                </div>
                <span
                  aria-label={`CTA type: ${CTA_TYPE_LABELS[brief.ctaType]}`}
                  style={{
                    fontSize: 11,
                    padding: "2px 8px",
                    borderRadius: 10,
                    whiteSpace: "nowrap",
                    background: CTA_TYPE_COLORS[brief.ctaType].bg,
                    color: CTA_TYPE_COLORS[brief.ctaType].fg,
                  }}
                >
                  {CTA_TYPE_LABELS[brief.ctaType]}
                </span>
                <button
                  type="button"
                  onClick={() => onCompose(brief)}
                  aria-label={`Compose caption for day ${brief.day}`}
                  title="Open this day in the Caption Composer"
                  style={{
                    flex: "0 0 auto",
                    padding: "6px 12px",
                    background: "var(--btn-primary, #0066cc)",
                    color: "white",
                    border: "none",
                    borderRadius: 4,
                    cursor: "pointer",
                    fontSize: 12,
                    whiteSpace: "nowrap",
                  }}
                >
                  ✍️ Compose
                </button>
              </li>
            ))}
          </ol>
          <p style={{ margin: "10px 0 0 0", fontSize: 12, color: "var(--text-muted, #888)" }}>
            {language.toUpperCase()} · Tap <strong>Compose</strong> on a day to build its full caption in the Single Post tab.
          </p>
        </section>
      )}
    </div>
  );
}

// ─── LeadCtaCard ─────────────────────────────────────────────────────────────

interface LeadCtaCardProps {
  index: number;
  lead: IgWizardLeadPackage;
  ruleCreated: boolean;
  creating: boolean;
  onCopy: () => void;
  onCreateRule: () => void;
  onUseInComposer: () => void;
}

/**
 * Renders a single Lead-CTA package: the CTA caption line, the trigger keyword
 * badge, the DM-template preview, and a "Create Auto-DM Rule" button that
 * wires the package into the Auto-DM tab in one click. Disabled + checkmark
 * once the rule has been created in this session.
 */
function LeadCtaCard({ index, lead, ruleCreated, creating, onCopy, onCreateRule, onUseInComposer }: LeadCtaCardProps) {
  const canCreate = Boolean(lead.trigger && lead.dmTemplate);
  return (
    <article
      style={{
        background: "var(--card-bg, #f8f8f8)",
        border: "1px solid var(--border, #ddd)",
        borderRadius: 6,
        padding: 10,
        display: "grid",
        gap: 6,
      }}
      aria-label={`Lead CTA ${index + 1} with trigger ${lead.trigger || "unknown"}`}
    >
      <div style={{ display: "flex", alignItems: "flex-start", gap: 8 }}>
        <span style={{ color: "var(--text-muted, #888)", fontSize: 13, paddingTop: 2 }}>{index + 1}.</span>
        <button
          type="button"
          onClick={onCopy}
          aria-label={`Copy CTA: ${lead.cta}`}
          style={{
            flex: 1,
            textAlign: "left",
            background: "transparent",
            border: "none",
            padding: 0,
            cursor: "pointer",
            fontSize: 14,
            color: "var(--text, #333)",
          }}
        >
          {lead.cta}
        </button>
        {lead.trigger && (
          <span
            aria-label={`Trigger keyword: ${lead.trigger}`}
            style={{
              fontFamily: "monospace",
              fontSize: 12,
              padding: "2px 6px",
              background: "var(--badge-bg, #e8f0fe)",
              color: "var(--badge-text, #1565c0)",
              borderRadius: 3,
              whiteSpace: "nowrap",
            }}
          >
            {lead.trigger}
          </span>
        )}
      </div>
      {lead.dmTemplate && (
        <div
          aria-label="Suggested DM template"
          style={{
            fontSize: 12,
            color: "var(--text-muted, #666)",
            background: "var(--code-bg, #fff)",
            border: "1px dashed var(--border, #ddd)",
            borderRadius: 4,
            padding: "6px 8px",
            fontFamily: "system-ui, sans-serif",
            whiteSpace: "pre-wrap",
          }}
        >
          <span style={{ fontWeight: 600, color: "var(--text-muted, #888)" }}>DM reply:</span>{" "}
          {lead.dmTemplate}
        </div>
      )}
      <div style={{ display: "flex", gap: 8, justifyContent: "flex-end", marginTop: 2 }}>
        <button
          type="button"
          onClick={onUseInComposer}
          aria-label={`Use this CTA in the caption composer: ${lead.cta}`}
          title="Use in Caption Composer"
          style={{
            fontSize: 12,
            padding: "4px 10px",
            background: "transparent",
            color: "var(--text, #333)",
            border: "1px solid var(--border, #ddd)",
            borderRadius: 4,
            cursor: "pointer",
          }}
        >
          ✍️ Use
        </button>
        {ruleCreated ? (
          <span
            role="status"
            aria-label="Rule created"
            style={{
              fontSize: 12,
              padding: "4px 10px",
              background: "var(--success-bg, #e6f4ea)",
              color: "var(--success-text, #137333)",
              borderRadius: 4,
              fontWeight: 500,
            }}
          >
            ✓ Auto-DM rule created
          </span>
        ) : (
          <button
            type="button"
            onClick={onCreateRule}
            disabled={!canCreate || creating}
            aria-label={`Create Auto-DM rule for trigger ${lead.trigger}`}
            title={
              canCreate
                ? "Create an Instagram Auto-DM rule from this package (you can edit it later in the Auto-DM tab)"
                : "This lead is missing a trigger keyword or DM template — re-generate."
            }
            style={{
              fontSize: 12,
              padding: "4px 10px",
              background: !canCreate || creating ? "var(--btn-disabled, #ccc)" : "var(--btn-primary, #0066cc)",
              color: "white",
              border: "none",
              borderRadius: 4,
              cursor: !canCreate || creating ? "not-allowed" : "pointer",
              fontWeight: 500,
            }}
          >
            {creating ? "Creating…" : "Create Auto-DM Rule"}
          </button>
        )}
      </div>
    </article>
  );
}
